# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sipilla/Documents/DEV/libtypec

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sipilla/Documents/DEV/libtypec

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/sipilla/Documents/DEV/libtypec/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sipilla/Documents/DEV/libtypec/CMakeFiles /home/sipilla/Documents/DEV/libtypec//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sipilla/Documents/DEV/libtypec/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libtypec

# Build rule for target.
libtypec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libtypec
.PHONY : libtypec

# fast build rule for target.
libtypec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/build
.PHONY : libtypec/fast

#=============================================================================
# Target rules for targets named lstypec

# Build rule for target.
lstypec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lstypec
.PHONY : lstypec

# fast build rule for target.
lstypec/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/lstypec.dir/build.make utils/CMakeFiles/lstypec.dir/build
.PHONY : lstypec/fast

#=============================================================================
# Target rules for targets named typecstatus

# Build rule for target.
typecstatus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 typecstatus
.PHONY : typecstatus

# fast build rule for target.
typecstatus/fast:
	$(MAKE) $(MAKESILENT) -f utils/CMakeFiles/typecstatus.dir/build.make utils/CMakeFiles/typecstatus.dir/build
.PHONY : typecstatus/fast

libtypec.o: libtypec.c.o
.PHONY : libtypec.o

# target to build an object file
libtypec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec.c.o
.PHONY : libtypec.c.o

libtypec.i: libtypec.c.i
.PHONY : libtypec.i

# target to preprocess a source file
libtypec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec.c.i
.PHONY : libtypec.c.i

libtypec.s: libtypec.c.s
.PHONY : libtypec.s

# target to generate assembly for a file
libtypec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec.c.s
.PHONY : libtypec.c.s

libtypec_dbgfs_ops.o: libtypec_dbgfs_ops.c.o
.PHONY : libtypec_dbgfs_ops.o

# target to build an object file
libtypec_dbgfs_ops.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec_dbgfs_ops.c.o
.PHONY : libtypec_dbgfs_ops.c.o

libtypec_dbgfs_ops.i: libtypec_dbgfs_ops.c.i
.PHONY : libtypec_dbgfs_ops.i

# target to preprocess a source file
libtypec_dbgfs_ops.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec_dbgfs_ops.c.i
.PHONY : libtypec_dbgfs_ops.c.i

libtypec_dbgfs_ops.s: libtypec_dbgfs_ops.c.s
.PHONY : libtypec_dbgfs_ops.s

# target to generate assembly for a file
libtypec_dbgfs_ops.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec_dbgfs_ops.c.s
.PHONY : libtypec_dbgfs_ops.c.s

libtypec_sysfs_ops.o: libtypec_sysfs_ops.c.o
.PHONY : libtypec_sysfs_ops.o

# target to build an object file
libtypec_sysfs_ops.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec_sysfs_ops.c.o
.PHONY : libtypec_sysfs_ops.c.o

libtypec_sysfs_ops.i: libtypec_sysfs_ops.c.i
.PHONY : libtypec_sysfs_ops.i

# target to preprocess a source file
libtypec_sysfs_ops.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec_sysfs_ops.c.i
.PHONY : libtypec_sysfs_ops.c.i

libtypec_sysfs_ops.s: libtypec_sysfs_ops.c.s
.PHONY : libtypec_sysfs_ops.s

# target to generate assembly for a file
libtypec_sysfs_ops.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtypec.dir/build.make CMakeFiles/libtypec.dir/libtypec_sysfs_ops.c.s
.PHONY : libtypec_sysfs_ops.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... libtypec"
	@echo "... lstypec"
	@echo "... typecstatus"
	@echo "... libtypec.o"
	@echo "... libtypec.i"
	@echo "... libtypec.s"
	@echo "... libtypec_dbgfs_ops.o"
	@echo "... libtypec_dbgfs_ops.i"
	@echo "... libtypec_dbgfs_ops.s"
	@echo "... libtypec_sysfs_ops.o"
	@echo "... libtypec_sysfs_ops.i"
	@echo "... libtypec_sysfs_ops.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

